### ISSUE TITLE
yAgents vs yWorkflows

### ISSUE THREAD

**Issue by seshubonam** [yeagerai/yeagerai-agent#5]
Wondering if yWorkflows are still relevant in the yAgents application. 

incredible work so far and this project needs more attention. when an app on top of this goes viral, people will realise the potential. I've seen some no-code ai app builders offering ui tools and promising something like yAgents under the hood. but its just demos mostly. checkout: imagica.ai and brancher.ai .. may be you could work on UI as well to monetise this tech better. since one of your goals is to help yAgents to be monetised, ai apps with cool interfaces built on top of yAgents are actually monetisable.

**Comment by jmlago** [comment]
yWorkflows will be discontinued, as it is now being replaced by yAgents. There have been several refactors and changes that make yAgents much more powerful.
