### ISSUE TITLE
Problem with multi-line prompt deleting input

### ISSUE THREAD

**Issue by MuncleUscles** [yeagerai/yeagerai-agent#6]
When entering a prompt that breaks into a new line, pressing backspace to delete input only works until the start of the line.

Afterwards it keeps deleting characters (because the final prompt comes out broken) but visually the cursor is stuck on the new line and isn't deleting input.

System: WSL on Windows 11

**Comment by jmlago** [comment]
I'm fixing that with the new gradio local UI, I'll share here the PR once finished

**Comment by jmlago** [comment]
fixed here:
https://github.com/yeagerai/yeagerai-agent/pull/12
